# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: my@mail.com
author_name: CiottiGiorgio
contract_name: digital_marketplace
deployment_language: python
preset_name: production
project_name: py-dm-intermediate-en

