# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.5
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: giorgio.ciotti@algorand.foundation
author_name: CiottiGiorgio
cloud_provider: none
preset_name: production
project_name: py-dm-intermediate-en-frontend

